#!/bin/sh

set -eu
set -x

SOURCE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BUILD_TYPE=${BUILD_TYPE:-Release}
BUILD_DIR=${BUILD_DIR:-"$SOURCE_DIR/out/build/linux-${BUILD_TYPE}"}
INSTALL_DIR=${INSTALL_DIR:-"$SOURCE_DIR/out/install/linux-${BUILD_TYPE}"}
GENERATOR=${GENERATOR:-Ninja}
BUILD_EXAMPLES=${BUILD_EXAMPLES:-ON}
ENABLE_PROTOBUF=${ENABLE_PROTOBUF:-ON}

cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -G "$GENERATOR" \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DMUDUO_BUILD_EXAMPLES="$BUILD_EXAMPLES" \
  -DMUDUO_ENABLE_PROTOBUF="$ENABLE_PROTOBUF"

ln -sf "$BUILD_DIR/compile_commands.json" "$SOURCE_DIR/compile_commands.json"

cmake --build "$BUILD_DIR" -- "$@"

# Run tests with:
# CTEST_OUTPUT_ON_FAILURE=TRUE cmake --build "$BUILD_DIR" --target test
